# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michel/Desktop/ENSIIE/S3/PIMA/Moteur-Graphique

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michel/Desktop/ENSIIE/S3/PIMA/Moteur-Graphique

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michel/Desktop/ENSIIE/S3/PIMA/Moteur-Graphique/CMakeFiles /home/michel/Desktop/ENSIIE/S3/PIMA/Moteur-Graphique/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michel/Desktop/ENSIIE/S3/PIMA/Moteur-Graphique/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/engine/Abstract_Renderer.o: src/engine/Abstract_Renderer.cpp.o

.PHONY : src/engine/Abstract_Renderer.o

# target to build an object file
src/engine/Abstract_Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/Abstract_Renderer.cpp.o
.PHONY : src/engine/Abstract_Renderer.cpp.o

src/engine/Abstract_Renderer.i: src/engine/Abstract_Renderer.cpp.i

.PHONY : src/engine/Abstract_Renderer.i

# target to preprocess a source file
src/engine/Abstract_Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/Abstract_Renderer.cpp.i
.PHONY : src/engine/Abstract_Renderer.cpp.i

src/engine/Abstract_Renderer.s: src/engine/Abstract_Renderer.cpp.s

.PHONY : src/engine/Abstract_Renderer.s

# target to generate assembly for a file
src/engine/Abstract_Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/Abstract_Renderer.cpp.s
.PHONY : src/engine/Abstract_Renderer.cpp.s

src/engine/GraphicsEngine.o: src/engine/GraphicsEngine.cpp.o

.PHONY : src/engine/GraphicsEngine.o

# target to build an object file
src/engine/GraphicsEngine.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/GraphicsEngine.cpp.o
.PHONY : src/engine/GraphicsEngine.cpp.o

src/engine/GraphicsEngine.i: src/engine/GraphicsEngine.cpp.i

.PHONY : src/engine/GraphicsEngine.i

# target to preprocess a source file
src/engine/GraphicsEngine.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/GraphicsEngine.cpp.i
.PHONY : src/engine/GraphicsEngine.cpp.i

src/engine/GraphicsEngine.s: src/engine/GraphicsEngine.cpp.s

.PHONY : src/engine/GraphicsEngine.s

# target to generate assembly for a file
src/engine/GraphicsEngine.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/engine/GraphicsEngine.cpp.s
.PHONY : src/engine/GraphicsEngine.cpp.s

src/environment/ApparenceProperties.o: src/environment/ApparenceProperties.cpp.o

.PHONY : src/environment/ApparenceProperties.o

# target to build an object file
src/environment/ApparenceProperties.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/ApparenceProperties.cpp.o
.PHONY : src/environment/ApparenceProperties.cpp.o

src/environment/ApparenceProperties.i: src/environment/ApparenceProperties.cpp.i

.PHONY : src/environment/ApparenceProperties.i

# target to preprocess a source file
src/environment/ApparenceProperties.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/ApparenceProperties.cpp.i
.PHONY : src/environment/ApparenceProperties.cpp.i

src/environment/ApparenceProperties.s: src/environment/ApparenceProperties.cpp.s

.PHONY : src/environment/ApparenceProperties.s

# target to generate assembly for a file
src/environment/ApparenceProperties.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/ApparenceProperties.cpp.s
.PHONY : src/environment/ApparenceProperties.cpp.s

src/environment/Camera.o: src/environment/Camera.cpp.o

.PHONY : src/environment/Camera.o

# target to build an object file
src/environment/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Camera.cpp.o
.PHONY : src/environment/Camera.cpp.o

src/environment/Camera.i: src/environment/Camera.cpp.i

.PHONY : src/environment/Camera.i

# target to preprocess a source file
src/environment/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Camera.cpp.i
.PHONY : src/environment/Camera.cpp.i

src/environment/Camera.s: src/environment/Camera.cpp.s

.PHONY : src/environment/Camera.s

# target to generate assembly for a file
src/environment/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Camera.cpp.s
.PHONY : src/environment/Camera.cpp.s

src/environment/CoordinatesHandler.o: src/environment/CoordinatesHandler.cpp.o

.PHONY : src/environment/CoordinatesHandler.o

# target to build an object file
src/environment/CoordinatesHandler.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/CoordinatesHandler.cpp.o
.PHONY : src/environment/CoordinatesHandler.cpp.o

src/environment/CoordinatesHandler.i: src/environment/CoordinatesHandler.cpp.i

.PHONY : src/environment/CoordinatesHandler.i

# target to preprocess a source file
src/environment/CoordinatesHandler.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/CoordinatesHandler.cpp.i
.PHONY : src/environment/CoordinatesHandler.cpp.i

src/environment/CoordinatesHandler.s: src/environment/CoordinatesHandler.cpp.s

.PHONY : src/environment/CoordinatesHandler.s

# target to generate assembly for a file
src/environment/CoordinatesHandler.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/CoordinatesHandler.cpp.s
.PHONY : src/environment/CoordinatesHandler.cpp.s

src/environment/Environment.o: src/environment/Environment.cpp.o

.PHONY : src/environment/Environment.o

# target to build an object file
src/environment/Environment.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Environment.cpp.o
.PHONY : src/environment/Environment.cpp.o

src/environment/Environment.i: src/environment/Environment.cpp.i

.PHONY : src/environment/Environment.i

# target to preprocess a source file
src/environment/Environment.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Environment.cpp.i
.PHONY : src/environment/Environment.cpp.i

src/environment/Environment.s: src/environment/Environment.cpp.s

.PHONY : src/environment/Environment.s

# target to generate assembly for a file
src/environment/Environment.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Environment.cpp.s
.PHONY : src/environment/Environment.cpp.s

src/environment/MappedTexture.o: src/environment/MappedTexture.cpp.o

.PHONY : src/environment/MappedTexture.o

# target to build an object file
src/environment/MappedTexture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/MappedTexture.cpp.o
.PHONY : src/environment/MappedTexture.cpp.o

src/environment/MappedTexture.i: src/environment/MappedTexture.cpp.i

.PHONY : src/environment/MappedTexture.i

# target to preprocess a source file
src/environment/MappedTexture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/MappedTexture.cpp.i
.PHONY : src/environment/MappedTexture.cpp.i

src/environment/MappedTexture.s: src/environment/MappedTexture.cpp.s

.PHONY : src/environment/MappedTexture.s

# target to generate assembly for a file
src/environment/MappedTexture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/MappedTexture.cpp.s
.PHONY : src/environment/MappedTexture.cpp.s

src/environment/Object.o: src/environment/Object.cpp.o

.PHONY : src/environment/Object.o

# target to build an object file
src/environment/Object.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Object.cpp.o
.PHONY : src/environment/Object.cpp.o

src/environment/Object.i: src/environment/Object.cpp.i

.PHONY : src/environment/Object.i

# target to preprocess a source file
src/environment/Object.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Object.cpp.i
.PHONY : src/environment/Object.cpp.i

src/environment/Object.s: src/environment/Object.cpp.s

.PHONY : src/environment/Object.s

# target to generate assembly for a file
src/environment/Object.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Object.cpp.s
.PHONY : src/environment/Object.cpp.s

src/environment/RegularObjects/Sphere.o: src/environment/RegularObjects/Sphere.cpp.o

.PHONY : src/environment/RegularObjects/Sphere.o

# target to build an object file
src/environment/RegularObjects/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/RegularObjects/Sphere.cpp.o
.PHONY : src/environment/RegularObjects/Sphere.cpp.o

src/environment/RegularObjects/Sphere.i: src/environment/RegularObjects/Sphere.cpp.i

.PHONY : src/environment/RegularObjects/Sphere.i

# target to preprocess a source file
src/environment/RegularObjects/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/RegularObjects/Sphere.cpp.i
.PHONY : src/environment/RegularObjects/Sphere.cpp.i

src/environment/RegularObjects/Sphere.s: src/environment/RegularObjects/Sphere.cpp.s

.PHONY : src/environment/RegularObjects/Sphere.s

# target to generate assembly for a file
src/environment/RegularObjects/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/RegularObjects/Sphere.cpp.s
.PHONY : src/environment/RegularObjects/Sphere.cpp.s

src/environment/Tessel.o: src/environment/Tessel.cpp.o

.PHONY : src/environment/Tessel.o

# target to build an object file
src/environment/Tessel.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Tessel.cpp.o
.PHONY : src/environment/Tessel.cpp.o

src/environment/Tessel.i: src/environment/Tessel.cpp.i

.PHONY : src/environment/Tessel.i

# target to preprocess a source file
src/environment/Tessel.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Tessel.cpp.i
.PHONY : src/environment/Tessel.cpp.i

src/environment/Tessel.s: src/environment/Tessel.cpp.s

.PHONY : src/environment/Tessel.s

# target to generate assembly for a file
src/environment/Tessel.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/environment/Tessel.cpp.s
.PHONY : src/environment/Tessel.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/raytracer/RT_Ray.o: src/raytracer/RT_Ray.cpp.o

.PHONY : src/raytracer/RT_Ray.o

# target to build an object file
src/raytracer/RT_Ray.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_Ray.cpp.o
.PHONY : src/raytracer/RT_Ray.cpp.o

src/raytracer/RT_Ray.i: src/raytracer/RT_Ray.cpp.i

.PHONY : src/raytracer/RT_Ray.i

# target to preprocess a source file
src/raytracer/RT_Ray.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_Ray.cpp.i
.PHONY : src/raytracer/RT_Ray.cpp.i

src/raytracer/RT_Ray.s: src/raytracer/RT_Ray.cpp.s

.PHONY : src/raytracer/RT_Ray.s

# target to generate assembly for a file
src/raytracer/RT_Ray.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_Ray.cpp.s
.PHONY : src/raytracer/RT_Ray.cpp.s

src/raytracer/RT_RayCaster.o: src/raytracer/RT_RayCaster.cpp.o

.PHONY : src/raytracer/RT_RayCaster.o

# target to build an object file
src/raytracer/RT_RayCaster.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayCaster.cpp.o
.PHONY : src/raytracer/RT_RayCaster.cpp.o

src/raytracer/RT_RayCaster.i: src/raytracer/RT_RayCaster.cpp.i

.PHONY : src/raytracer/RT_RayCaster.i

# target to preprocess a source file
src/raytracer/RT_RayCaster.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayCaster.cpp.i
.PHONY : src/raytracer/RT_RayCaster.cpp.i

src/raytracer/RT_RayCaster.s: src/raytracer/RT_RayCaster.cpp.s

.PHONY : src/raytracer/RT_RayCaster.s

# target to generate assembly for a file
src/raytracer/RT_RayCaster.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayCaster.cpp.s
.PHONY : src/raytracer/RT_RayCaster.cpp.s

src/raytracer/RT_RayEnvIntersector.o: src/raytracer/RT_RayEnvIntersector.cpp.o

.PHONY : src/raytracer/RT_RayEnvIntersector.o

# target to build an object file
src/raytracer/RT_RayEnvIntersector.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayEnvIntersector.cpp.o
.PHONY : src/raytracer/RT_RayEnvIntersector.cpp.o

src/raytracer/RT_RayEnvIntersector.i: src/raytracer/RT_RayEnvIntersector.cpp.i

.PHONY : src/raytracer/RT_RayEnvIntersector.i

# target to preprocess a source file
src/raytracer/RT_RayEnvIntersector.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayEnvIntersector.cpp.i
.PHONY : src/raytracer/RT_RayEnvIntersector.cpp.i

src/raytracer/RT_RayEnvIntersector.s: src/raytracer/RT_RayEnvIntersector.cpp.s

.PHONY : src/raytracer/RT_RayEnvIntersector.s

# target to generate assembly for a file
src/raytracer/RT_RayEnvIntersector.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayEnvIntersector.cpp.s
.PHONY : src/raytracer/RT_RayEnvIntersector.cpp.s

src/raytracer/RT_RayTracer.o: src/raytracer/RT_RayTracer.cpp.o

.PHONY : src/raytracer/RT_RayTracer.o

# target to build an object file
src/raytracer/RT_RayTracer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayTracer.cpp.o
.PHONY : src/raytracer/RT_RayTracer.cpp.o

src/raytracer/RT_RayTracer.i: src/raytracer/RT_RayTracer.cpp.i

.PHONY : src/raytracer/RT_RayTracer.i

# target to preprocess a source file
src/raytracer/RT_RayTracer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayTracer.cpp.i
.PHONY : src/raytracer/RT_RayTracer.cpp.i

src/raytracer/RT_RayTracer.s: src/raytracer/RT_RayTracer.cpp.s

.PHONY : src/raytracer/RT_RayTracer.s

# target to generate assembly for a file
src/raytracer/RT_RayTracer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/raytracer/RT_RayTracer.cpp.s
.PHONY : src/raytracer/RT_RayTracer.cpp.s

src/userInterface/CommandLineInterface.o: src/userInterface/CommandLineInterface.cpp.o

.PHONY : src/userInterface/CommandLineInterface.o

# target to build an object file
src/userInterface/CommandLineInterface.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/CommandLineInterface.cpp.o
.PHONY : src/userInterface/CommandLineInterface.cpp.o

src/userInterface/CommandLineInterface.i: src/userInterface/CommandLineInterface.cpp.i

.PHONY : src/userInterface/CommandLineInterface.i

# target to preprocess a source file
src/userInterface/CommandLineInterface.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/CommandLineInterface.cpp.i
.PHONY : src/userInterface/CommandLineInterface.cpp.i

src/userInterface/CommandLineInterface.s: src/userInterface/CommandLineInterface.cpp.s

.PHONY : src/userInterface/CommandLineInterface.s

# target to generate assembly for a file
src/userInterface/CommandLineInterface.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/CommandLineInterface.cpp.s
.PHONY : src/userInterface/CommandLineInterface.cpp.s

src/userInterface/GraphicalUserInterface.o: src/userInterface/GraphicalUserInterface.cpp.o

.PHONY : src/userInterface/GraphicalUserInterface.o

# target to build an object file
src/userInterface/GraphicalUserInterface.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/GraphicalUserInterface.cpp.o
.PHONY : src/userInterface/GraphicalUserInterface.cpp.o

src/userInterface/GraphicalUserInterface.i: src/userInterface/GraphicalUserInterface.cpp.i

.PHONY : src/userInterface/GraphicalUserInterface.i

# target to preprocess a source file
src/userInterface/GraphicalUserInterface.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/GraphicalUserInterface.cpp.i
.PHONY : src/userInterface/GraphicalUserInterface.cpp.i

src/userInterface/GraphicalUserInterface.s: src/userInterface/GraphicalUserInterface.cpp.s

.PHONY : src/userInterface/GraphicalUserInterface.s

# target to generate assembly for a file
src/userInterface/GraphicalUserInterface.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/userInterface/GraphicalUserInterface.cpp.s
.PHONY : src/userInterface/GraphicalUserInterface.cpp.s

src/utils/Color.o: src/utils/Color.cpp.o

.PHONY : src/utils/Color.o

# target to build an object file
src/utils/Color.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Color.cpp.o
.PHONY : src/utils/Color.cpp.o

src/utils/Color.i: src/utils/Color.cpp.i

.PHONY : src/utils/Color.i

# target to preprocess a source file
src/utils/Color.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Color.cpp.i
.PHONY : src/utils/Color.cpp.i

src/utils/Color.s: src/utils/Color.cpp.s

.PHONY : src/utils/Color.s

# target to generate assembly for a file
src/utils/Color.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Color.cpp.s
.PHONY : src/utils/Color.cpp.s

src/utils/OutputPictureManager.o: src/utils/OutputPictureManager.cpp.o

.PHONY : src/utils/OutputPictureManager.o

# target to build an object file
src/utils/OutputPictureManager.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/OutputPictureManager.cpp.o
.PHONY : src/utils/OutputPictureManager.cpp.o

src/utils/OutputPictureManager.i: src/utils/OutputPictureManager.cpp.i

.PHONY : src/utils/OutputPictureManager.i

# target to preprocess a source file
src/utils/OutputPictureManager.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/OutputPictureManager.cpp.i
.PHONY : src/utils/OutputPictureManager.cpp.i

src/utils/OutputPictureManager.s: src/utils/OutputPictureManager.cpp.s

.PHONY : src/utils/OutputPictureManager.s

# target to generate assembly for a file
src/utils/OutputPictureManager.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/OutputPictureManager.cpp.s
.PHONY : src/utils/OutputPictureManager.cpp.s

src/utils/Point3D.o: src/utils/Point3D.cpp.o

.PHONY : src/utils/Point3D.o

# target to build an object file
src/utils/Point3D.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Point3D.cpp.o
.PHONY : src/utils/Point3D.cpp.o

src/utils/Point3D.i: src/utils/Point3D.cpp.i

.PHONY : src/utils/Point3D.i

# target to preprocess a source file
src/utils/Point3D.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Point3D.cpp.i
.PHONY : src/utils/Point3D.cpp.i

src/utils/Point3D.s: src/utils/Point3D.cpp.s

.PHONY : src/utils/Point3D.s

# target to generate assembly for a file
src/utils/Point3D.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Point3D.cpp.s
.PHONY : src/utils/Point3D.cpp.s

src/utils/Vector.o: src/utils/Vector.cpp.o

.PHONY : src/utils/Vector.o

# target to build an object file
src/utils/Vector.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Vector.cpp.o
.PHONY : src/utils/Vector.cpp.o

src/utils/Vector.i: src/utils/Vector.cpp.i

.PHONY : src/utils/Vector.i

# target to preprocess a source file
src/utils/Vector.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Vector.cpp.i
.PHONY : src/utils/Vector.cpp.i

src/utils/Vector.s: src/utils/Vector.cpp.s

.PHONY : src/utils/Vector.s

# target to generate assembly for a file
src/utils/Vector.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/utils/Vector.cpp.s
.PHONY : src/utils/Vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... src/engine/Abstract_Renderer.o"
	@echo "... src/engine/Abstract_Renderer.i"
	@echo "... src/engine/Abstract_Renderer.s"
	@echo "... src/engine/GraphicsEngine.o"
	@echo "... src/engine/GraphicsEngine.i"
	@echo "... src/engine/GraphicsEngine.s"
	@echo "... src/environment/ApparenceProperties.o"
	@echo "... src/environment/ApparenceProperties.i"
	@echo "... src/environment/ApparenceProperties.s"
	@echo "... src/environment/Camera.o"
	@echo "... src/environment/Camera.i"
	@echo "... src/environment/Camera.s"
	@echo "... src/environment/CoordinatesHandler.o"
	@echo "... src/environment/CoordinatesHandler.i"
	@echo "... src/environment/CoordinatesHandler.s"
	@echo "... src/environment/Environment.o"
	@echo "... src/environment/Environment.i"
	@echo "... src/environment/Environment.s"
	@echo "... src/environment/MappedTexture.o"
	@echo "... src/environment/MappedTexture.i"
	@echo "... src/environment/MappedTexture.s"
	@echo "... src/environment/Object.o"
	@echo "... src/environment/Object.i"
	@echo "... src/environment/Object.s"
	@echo "... src/environment/RegularObjects/Sphere.o"
	@echo "... src/environment/RegularObjects/Sphere.i"
	@echo "... src/environment/RegularObjects/Sphere.s"
	@echo "... src/environment/Tessel.o"
	@echo "... src/environment/Tessel.i"
	@echo "... src/environment/Tessel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/raytracer/RT_Ray.o"
	@echo "... src/raytracer/RT_Ray.i"
	@echo "... src/raytracer/RT_Ray.s"
	@echo "... src/raytracer/RT_RayCaster.o"
	@echo "... src/raytracer/RT_RayCaster.i"
	@echo "... src/raytracer/RT_RayCaster.s"
	@echo "... src/raytracer/RT_RayEnvIntersector.o"
	@echo "... src/raytracer/RT_RayEnvIntersector.i"
	@echo "... src/raytracer/RT_RayEnvIntersector.s"
	@echo "... src/raytracer/RT_RayTracer.o"
	@echo "... src/raytracer/RT_RayTracer.i"
	@echo "... src/raytracer/RT_RayTracer.s"
	@echo "... src/userInterface/CommandLineInterface.o"
	@echo "... src/userInterface/CommandLineInterface.i"
	@echo "... src/userInterface/CommandLineInterface.s"
	@echo "... src/userInterface/GraphicalUserInterface.o"
	@echo "... src/userInterface/GraphicalUserInterface.i"
	@echo "... src/userInterface/GraphicalUserInterface.s"
	@echo "... src/utils/Color.o"
	@echo "... src/utils/Color.i"
	@echo "... src/utils/Color.s"
	@echo "... src/utils/OutputPictureManager.o"
	@echo "... src/utils/OutputPictureManager.i"
	@echo "... src/utils/OutputPictureManager.s"
	@echo "... src/utils/Point3D.o"
	@echo "... src/utils/Point3D.i"
	@echo "... src/utils/Point3D.s"
	@echo "... src/utils/Vector.o"
	@echo "... src/utils/Vector.i"
	@echo "... src/utils/Vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

